import { StyleSheet } from "@react-pdf/renderer";
import { LEASE_PDF_FONT_FAMILY } from "./leasePdfFont";
import { leasePdfColors as C } from "./leasePdfTheme";

const F = LEASE_PDF_FONT_FAMILY;

export const leasePdfStyles = StyleSheet.create({
 page: {
  fontFamily: F,
  fontWeight: 400,
  fontSize: 9.5,
  paddingTop: 40,
  paddingBottom: 52,
  paddingHorizontal: 44,
  lineHeight: 1.5,
  color: C.text,
  backgroundColor: C.paper,
 },
 topBand: {
  position: "absolute",
  top: 0,
  left: 0,
  right: 0,
  height: 6,
  backgroundColor: C.accent,
 },
 hero: {
  marginBottom: 22,
  paddingBottom: 14,
  borderBottomWidth: 1,
  borderBottomColor: C.rule,
 },
 docTitle: {
  fontFamily: F,
  fontWeight: 700,
  fontSize: 20,
  letterSpacing: 1.2,
  color: C.accent,
  marginBottom: 8,
  textAlign: "center",
 },
 docMeta: {
  fontFamily: F,
  fontWeight: 400,
  fontSize: 9,
  color: C.text,
  marginTop: 5,
  lineHeight: 1.55,
 },
 sectionWrap: {
  marginBottom: 16,
 },
 sectionHead: {
  flexDirection: "row",
  alignItems: "center",
  marginBottom: 10,
 },
 sectionNum: {
  width: 22,
  height: 22,
  borderRadius: 4,
  backgroundColor: C.accent,
  alignItems: "center",
  justifyContent: "center",
  marginRight: 10,
 },
 sectionNumText: {
  fontFamily: F,
  fontWeight: 700,
  fontSize: 10,
  color: "#fff",
 },
 sectionTitle: {
  fontFamily: F,
  fontWeight: 700,
  fontSize: 11,
  color: C.accent,
  letterSpacing: 0.6,
 },
 sectionTitleUnderlineWrap: {
  alignSelf: "flex-start",
  borderBottomWidth: 2,
  borderBottomColor: C.accent,
  paddingBottom: 3,
  marginBottom: 2,
 },
 panel: {
  backgroundColor: C.accentSoft,
  borderRadius: 6,
  padding: 12,
  borderLeftWidth: 3,
  borderLeftColor: C.accent,
 },
 fieldRow: {
  flexDirection: "row",
  marginBottom: 6,
  alignItems: "flex-start",
 },
 fieldLabel: {
  width: "32%",
  fontFamily: F,
  fontWeight: 700,
  fontSize: 8.5,
  color: C.muted,
 },
 fieldVal: {
  flex: 1,
  fontFamily: F,
  fontWeight: 400,
  fontSize: 9,
  lineHeight: 1.45,
 },
 table: {
  borderWidth: 1,
  borderColor: C.rule,
  borderRadius: 4,
  overflow: "hidden",
 },
 tableRow: {
  flexDirection: "row",
  borderBottomWidth: 1,
  borderBottomColor: C.rule,
  minHeight: 22,
 },
 tableRowLast: {
  borderBottomWidth: 0,
 },
 tableCellL: {
  width: "38%",
  backgroundColor: C.accentSoft,
  paddingVertical: 6,
  paddingHorizontal: 8,
  fontFamily: F,
  fontWeight: 700,
  fontSize: 8.5,
  color: C.accent,
 },
 tableCellR: {
  flex: 1,
  paddingVertical: 6,
  paddingHorizontal: 8,
  fontFamily: F,
  fontWeight: 400,
  fontSize: 9,
  lineHeight: 1.4,
 },
 prose: {
  fontFamily: F,
  fontWeight: 400,
  fontSize: 9,
  lineHeight: 1.55,
  color: C.text,
  marginBottom: 8,
 },
 bulletLine: {
  flexDirection: "row",
  marginBottom: 4,
  paddingLeft: 4,
 },
 bullet: {
  width: 12,
  fontFamily: F,
  fontWeight: 700,
  fontSize: 9,
  color: C.accent,
 },
 bulletText: {
  flex: 1,
  fontFamily: F,
  fontWeight: 400,
  fontSize: 9,
  lineHeight: 1.45,
 },
 sigRow: {
  flexDirection: "row",
  marginTop: 28,
  gap: 16,
 },
 sigCol: {
  flex: 1,
  borderTopWidth: 1,
  borderTopColor: C.text,
  paddingTop: 8,
 },
 sigTitle: {
  fontFamily: F,
  fontWeight: 700,
  fontSize: 9,
  color: C.accent,
  marginBottom: 16,
  textAlign: "center",
 },
 sigLine: {
  fontFamily: F,
  fontWeight: 400,
  fontSize: 8.5,
  color: C.muted,
  marginBottom: 10,
 },
 footerNote: {
  fontFamily: F,
  fontWeight: 400,
  fontSize: 7.5,
  color: C.muted,
  lineHeight: 1.4,
  marginTop: 12,
  padding: 10,
  backgroundColor: "#f8fafc",
  borderRadius: 4,
 },
 footerFixed: {
  position: "absolute",
  bottom: 22,
  left: 44,
  right: 44,
  fontFamily: F,
  fontWeight: 400,
  fontSize: 7.5,
  color: C.muted,
  textAlign: "center",
 },
 sigImgBottom: {
  width: 200,
  height: 52,
  marginTop: 4,
  marginBottom: 6,
  objectFit: "contain",
 },
 watermark: {
  position: "absolute",
  top: 120,
  left: 0,
  right: 0,
  opacity: 0.04,
  fontSize: 44,
  fontFamily: F,
  fontWeight: 700,
  color: C.accent,
  textAlign: "center",
 },
});
